/**
 * Generates src/environments/environment.prod.ts from Vercel environment variables.
 * Run automatically via the `prebuild` npm script before `ng build`.
 */

const fs = require('fs');
const path = require('path');

const required = [
  'FIREBASE_API_KEY',
  'FIREBASE_AUTH_DOMAIN',
  'FIREBASE_PROJECT_ID',
  'FIREBASE_STORAGE_BUCKET',
  'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID',
  'RECAPTCHA_SITE_KEY',
];

const missing = required.filter((key) => !process.env[key]);
if (missing.length > 0) {
  console.error(`[generate-env] Missing required environment variables:\n  ${missing.join('\n  ')}`);
  process.exit(1);
}

const content = `// AUTO-GENERATED by scripts/generate-env.js — do not edit manually.
export const environment = {
  production: true,
  apiBaseUrl: '${process.env['API_BASE_URL'] || 'https://room.luigitonno.at/api'}',
  firebaseConfig: {
    apiKey: '${process.env['FIREBASE_API_KEY']}',
    authDomain: '${process.env['FIREBASE_AUTH_DOMAIN']}',
    projectId: '${process.env['FIREBASE_PROJECT_ID']}',
    storageBucket: '${process.env['FIREBASE_STORAGE_BUCKET']}',
    messagingSenderId: '${process.env['FIREBASE_MESSAGING_SENDER_ID']}',
    appId: '${process.env['FIREBASE_APP_ID']}',
    measurementId: '${process.env['FIREBASE_MEASUREMENT_ID'] || ''}'
  },
  recaptchaSiteKey: '${process.env['RECAPTCHA_SITE_KEY']}'
};
`;

const outPath = path.join(__dirname, '../src/environments/environment.prod.ts');
fs.writeFileSync(outPath, content, 'utf8');
console.log('[generate-env] src/environments/environment.prod.ts generated successfully.');
